[package]
name = "model2vec-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokenizers = "0.13"
safetensors = "0.5"
ndarray = "0.15"
hf-hub = "0.3"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
serde_json = "1.0"

[dev-dependencies]
approx = "0.5"
serde_json = "1.0"